import com.tawrid.pages.ChangePasswordPage


ChangePasswordPage.verifyChangePasswordPopup()
ChangePasswordPage.enterOldPassword()
ChangePasswordPage.enterNewPassword()
ChangePasswordPage.enterConfirmNewPassword()
ChangePasswordPage.clickOnSubmit()
ChangePasswordPage.verifyChangePasswordSubmittedSuccessfully()
ChangePasswordPage.clickOkButton()