<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FunderCodeField</name>
   <tag></tag>
   <elementGuidId>5a0b9147-e8cb-4dff-9fb0-13b0e1cf4aa1</elementGuidId>
   <imagePath>Screenshots/Targets/Page_TAWRID - Working Capital Finance/ProfileSetupPage_FunderCodeField.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_TAWRID - Working Capital Finance/ProfileSetupPage_FunderCodeField.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fsourceCustCodeKeyWord&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fsourceCustCodeKeyWord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;fsourceCustCodeKeyWord&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7153c2a5-4296-4fda-8a02-6cdc99455f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>878a71a7-90cb-4233-a1a6-c82b509752e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput form-control input-sm</value>
      <webElementGuid>c21406fd-6225-47fe-bcd6-8cd5f3f9f7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fsourceCustCodeKeyWord</value>
      <webElementGuid>d1b6ded6-28f0-49b8-a8bb-e47f171efc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-model</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridModel.fsourceCustCodeKeyWord</value>
      <webElementGuid>6e4233b2-a67f-4fca-8777-726e8a6b3abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-model-options</name>
      <type>Main</type>
      <value>{ updateOn: fsComponentCtrl.fsGridConfig.updateOn}</value>
      <webElementGuid>fa991a9c-90e0-4143-846e-f246a84e1806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-trim</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f389ba25-3147-43fd-9631-432e7f731165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-tooltip-template</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.tooltipTemplateUrl</value>
      <webElementGuid>c1f71bfe-49e3-4273-b561-34601184e3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-enable</name>
      <type>Main</type>
      <value>!!fsComponentCtrl.fsGridCtrl.getTooltipMessage(fsComponentCtrl.fsGridConfig)</value>
      <webElementGuid>90a356b5-7919-413c-ac8e-3044fd5f2987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-class</name>
      <type>Main</type>
      <value>input-tooltip</value>
      <webElementGuid>8bce6cdf-e59b-4346-b641-620685ecc973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-trigger</name>
      <type>Main</type>
      <value>'focus keyup paste cut'</value>
      <webElementGuid>0fe9ed95-d9f8-4fd4-8874-f4a4c2d46455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-append-to-body</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>16ffff63-94ec-492d-9285-f7b4401cd26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>top-right</value>
      <webElementGuid>1d0cb528-cd68-4339-932a-286a139c22ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-uppercase</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.uppercase</value>
      <webElementGuid>2c237886-061a-43e1-a5b7-d496dd095e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-grid-filter</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.filter</value>
      <webElementGuid>b6e566d5-ccfb-47c5-8a73-d314facf732e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-grid-prefix</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.prefix</value>
      <webElementGuid>aeda7cf4-112e-4456-a832-8aa0151a048a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-focus</name>
      <type>Main</type>
      <value>focus=true</value>
      <webElementGuid>89b572b5-97e5-4d8e-82c1-0535cd815a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-blur</name>
      <type>Main</type>
      <value>focus=false</value>
      <webElementGuid>e97033ab-404b-4ce9-a556-c7f17cf4a7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fs-scope&quot;]/body[@class=&quot;app fs-scope v-scroll&quot;]/div[@class=&quot;app-view fs-scope&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/form[@class=&quot;fs-pristine fs-valid-date fs-valid-dateformatcheck fs-valid-holidaycheck fs-valid fs-valid-date-compare fs-valid-min fs-valid-max fs-valid-required fs-valid-remove fs-valid-dateformatcheck-remove fs-valid-holidaycheck-remove fs-valid-date-compare-remove&quot;]/fs-layout[@class=&quot;fs-isolate-scope&quot;]/div[@class=&quot;fsLayout container-fluid&quot;]/div[@class=&quot;row panel-group&quot;]/fs-group[@class=&quot;fs-scope fs-isolate-scope fsGroup&quot;]/div[@class=&quot;panel panel-default fs-scope anonymous title-no-bg operator-group inquiry-operator-2 col-md-12 col-xs-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row fs-scope&quot;]/fs-grid[@class=&quot;fs-scope fs-isolate-scope fsGrid&quot;]/div[@class=&quot;col-md-2 col-sm-12 col-xs-12&quot;]/fs-custom-select[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsCustomSelect form-group fs-scope&quot;]/div[@class=&quot;dropdown col-md-0 open&quot;]/div[@class=&quot;fsCustomSelectItem animated fadeInUp dropdown-menu&quot;]/fs-grid[@class=&quot;filter fs-scope fs-isolate-scope fsGrid&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12&quot;]/fs-text[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsText form-group fs-scope&quot;]/div[@class=&quot;col-md-0&quot;]/div[@class=&quot;edit&quot;]/input[@class=&quot;textInput form-control input-sm&quot;]</value>
      <webElementGuid>b9160cef-7592-4b47-99f0-437344eb4442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fsourceCustCodeKeyWord']</value>
      <webElementGuid>8cf44c1e-d85d-4e50-b6fb-db70f6d92099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fs-text/div/div/div/input</value>
      <webElementGuid>95036be9-5ad6-4bb0-b71b-36ee8ae64ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fsourceCustCodeKeyWord']</value>
      <webElementGuid>a484f957-0c4c-4844-a196-04b3f9d26009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
