<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OKButton</name>
   <tag></tag>
   <elementGuidId>3824a475-2a94-4f51-aeb4-ff5b3b20a63f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@class = 'submit-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.submit-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d3d16a3-89bd-4cae-bee6-5d07cc3533bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-button</value>
      <webElementGuid>5c8e59c9-3f1e-4c2e-af9e-b9400311a48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b6571e5-a447-4c31-997d-931dcfbcfbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>forwardSignonPage(document.forms[0])</value>
      <webElementGuid>923dc263-1748-46aa-a205-b52183f1bbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								  OK  
							</value>
      <webElementGuid>88570e5f-1018-48e3-aa70-1d91122b97c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_PageContainer_&quot;)/form[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;sigon-page-bg&quot;]/table[@class=&quot;signon-panel&quot;]/tbody[1]/tr[1]/td[@class=&quot;logon-bg&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;signoff-panel&quot;]/tbody[1]/tr[1]/td[@class=&quot;text-center&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;text-center&quot;]/div[2]/button[@class=&quot;submit-button&quot;]</value>
      <webElementGuid>9854c268-7e57-40a8-a705-2f60de2a5bc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>8ae7f339-efb8-41a9-b3e0-586ff7faf493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_PageContainer_']/form/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/div[2]/button</value>
      <webElementGuid>68c3c749-aa8a-4fe6-ad0c-2ba59cc3f7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password is changed.'])[1]/following::button[1]</value>
      <webElementGuid>6d05bdcb-bd80-4766-9881-8b7bc0368272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Changed Successfully'])[1]/following::button[1]</value>
      <webElementGuid>42aa1fcb-ce08-4b7b-885e-45b17669d61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>24696d13-7650-4174-9ab7-709a663985e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
								  OK  
							' or . = '
								  OK  
							')]</value>
      <webElementGuid>4db11151-d7f2-4ff5-aa7c-1a8c43bb8b1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
