<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CompanyNameField</name>
   <tag></tag>
   <elementGuidId>962a7f23-4c6d-48d6-b20c-948b7f6e8bd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;companyName&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'companyName' and @fs-model = 'fsComponentCtrl.fsGridModel.companyName']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'companyName' and @fs-model = 'fsComponentCtrl.fsGridModel.companyName' and @placeholder = 'Enter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d91cd9a9-46ca-4508-944f-870b9a88ca0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5d5643b-20f6-48b2-a168-09cb380baf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput form-control input-sm fs-valid-maxlength fs-invalid fs-invalid-required</value>
      <webElementGuid>65b5ffb8-384c-4e39-a808-e4551917fe1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyName</value>
      <webElementGuid>85ee2a1b-a826-4e9b-a095-feb6dfb67190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-model</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridModel.companyName</value>
      <webElementGuid>a8579ffa-17a8-42ae-875c-39be0253a5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-model-options</name>
      <type>Main</type>
      <value>{ updateOn: fsComponentCtrl.fsGridConfig.updateOn}</value>
      <webElementGuid>01290f5e-5080-4c11-bf8a-c2448cc5c45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-trim</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47bc137a-d395-4414-823b-bc840078905a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-tooltip-template</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.tooltipTemplateUrl</value>
      <webElementGuid>0980aa09-95ab-402b-915c-294242b4ec65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-enable</name>
      <type>Main</type>
      <value>!!fsComponentCtrl.fsGridCtrl.getTooltipMessage(fsComponentCtrl.fsGridConfig)</value>
      <webElementGuid>f32149c1-1bfa-40af-9055-32e3f894c8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-class</name>
      <type>Main</type>
      <value>input-tooltip</value>
      <webElementGuid>3ea7c5a2-69ae-4982-bb80-8fc1bf6de64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-trigger</name>
      <type>Main</type>
      <value>'focus keyup paste cut'</value>
      <webElementGuid>3d69b9db-6c00-4015-8573-c38fc5f1b831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-append-to-body</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0ff6cbc-95d9-41e7-a181-427a1ff9e880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>top-right</value>
      <webElementGuid>ad17045d-2cc0-45d2-a3eb-6bb50537f95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-uppercase</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.uppercase</value>
      <webElementGuid>d3868523-5b58-4da3-861b-4279e3232d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-grid-filter</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.filter</value>
      <webElementGuid>bfafa3c4-894f-469c-af34-ebfb1bde43ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>501173ab-0e1d-47cf-8a43-abaea2158da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-grid-prefix</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.prefix</value>
      <webElementGuid>72e88b3a-4b5b-4bfa-9134-94ee0c2af823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-focus</name>
      <type>Main</type>
      <value>focus=true</value>
      <webElementGuid>4b7d9f81-be68-4024-a07d-c41573a29989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-blur</name>
      <type>Main</type>
      <value>focus=false</value>
      <webElementGuid>eef45334-935e-44c5-be75-48d507c25bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fs-scope&quot;]/body[@class=&quot;app fs-scope v-scroll&quot;]/div[@class=&quot;app-view fs-scope&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/form[@class=&quot;fs-valid-patterncheck fs-valid-emailcheck fs-valid-maxlength fs-invalid fs-invalid-required fs-dirty&quot;]/div[@class=&quot;panel fs-tabset&quot;]/div[@class=&quot;panel-body fs-tabset-head&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tab-set&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/div[@class=&quot;panel-body fs-tabset-head&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tab-set&quot;]/div[@class=&quot;fs-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane fs-scope active&quot;]/div[@class=&quot;panel-body fs-scope&quot;]/fs-form[@class=&quot;fs-valid-patterncheck fs-valid-emailcheck fs-valid-maxlength fs-invalid fs-invalid-required fs-dirty&quot;]/div[@class=&quot;fs-scope&quot;]/fs-layout[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsLayout container-fluid&quot;]/div[@class=&quot;row panel-group&quot;]/fs-group[@class=&quot;fs-scope fs-isolate-scope fsGroup&quot;]/div[@class=&quot;panel panel-default fs-scope anonymous col-md-12 col-xs-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row fs-scope subRow&quot;]/fs-grid[@class=&quot;fs-scope fs-isolate-scope fsGrid&quot;]/div[@class=&quot;col-md-3 col-sm-12 col-xs-12&quot;]/fs-text[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsText form-group fs-scope&quot;]/div[@class=&quot;col-md-0&quot;]/div[@class=&quot;edit&quot;]/input[@class=&quot;textInput form-control input-sm fs-valid-maxlength fs-invalid fs-invalid-required&quot;]</value>
      <webElementGuid>4bcc75c6-fa38-41e5-91a8-75e8331a03cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'companyName' and @fs-model = 'fsComponentCtrl.fsGridModel.companyName' and @placeholder = 'Enter']</value>
      <webElementGuid>9d7da310-dad7-47ab-aea4-2e9865ef0d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='companyName']</value>
      <webElementGuid>369fb4e2-9345-44e6-b60b-481cf8fc0640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fs-grid[3]/div/fs-text/div/div/div/input</value>
      <webElementGuid>e99df8a5-b1ab-4b54-b874-445c0a26e3eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
