<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CompanyAddressField</name>
   <tag></tag>
   <elementGuidId>daee5cee-318c-4007-be5c-17135d986bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;companyAddr1&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'companyAddr1' and @fs-model = 'fsComponentCtrl.fsGridModel.companyAddr1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'companyAddr1' and @fs-model = 'fsComponentCtrl.fsGridModel.companyAddr1' and @placeholder = 'Enter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da11b117-5d4f-4608-824f-7b88e80aeb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff74c1a0-2030-44a9-aec0-02a9abd3efa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput form-control input-sm fs-valid fs-valid-maxlength</value>
      <webElementGuid>ba003aad-4c79-4742-8383-90f036e64332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyAddr1</value>
      <webElementGuid>001277a2-0cc4-4fda-987b-727accac34f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-model</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridModel.companyAddr1</value>
      <webElementGuid>11c87247-28f1-424a-b37c-0d8a00edbbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-model-options</name>
      <type>Main</type>
      <value>{ updateOn: fsComponentCtrl.fsGridConfig.updateOn}</value>
      <webElementGuid>4f37b277-3c13-492e-a847-bdd8caa43d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-trim</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6d32abf-2912-4f95-ac33-a85fcebb2e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-tooltip-template</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.tooltipTemplateUrl</value>
      <webElementGuid>b668498b-c700-4a69-ad4e-2e26f70b6a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-enable</name>
      <type>Main</type>
      <value>!!fsComponentCtrl.fsGridCtrl.getTooltipMessage(fsComponentCtrl.fsGridConfig)</value>
      <webElementGuid>7da46c17-5a06-4513-8558-3eeef9f8cd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-class</name>
      <type>Main</type>
      <value>input-tooltip</value>
      <webElementGuid>8c389d54-e883-4d66-ab7c-479de21801e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-trigger</name>
      <type>Main</type>
      <value>'focus keyup paste cut'</value>
      <webElementGuid>566eeb3e-cb95-43b9-9427-d7538bb4d4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-append-to-body</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e7589450-e59b-41c1-9a38-7023a162df3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>top-right</value>
      <webElementGuid>69b22dab-1fcb-4b9a-941a-f53ab67d53d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-uppercase</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.uppercase</value>
      <webElementGuid>c944ea56-f1f1-4120-aac4-4d2c9487caff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-grid-filter</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.filter</value>
      <webElementGuid>d7eb849c-3393-4e4b-8a57-5fa2800ffec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>3bc8e12d-ea97-46a7-b288-7b3f5e1bd66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-grid-prefix</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.prefix</value>
      <webElementGuid>3bc56bf9-698f-4593-a58a-9fdc25e87687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-focus</name>
      <type>Main</type>
      <value>focus=true</value>
      <webElementGuid>d6d0f420-28de-4251-ba71-f29740412729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-blur</name>
      <type>Main</type>
      <value>focus=false</value>
      <webElementGuid>3a3bd808-54d7-4a1d-8569-7a6b0164bb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fs-scope&quot;]/body[@class=&quot;app fs-scope v-scroll&quot;]/div[@class=&quot;app-view fs-scope&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/form[@class=&quot;fs-valid-patterncheck fs-valid-emailcheck fs-valid-maxlength fs-invalid fs-invalid-required fs-dirty fs-valid-parse fs-pending-add fs-invalid-remove fs-invalid-required-remove fs-valid-maxlength-remove fs-valid-patterncheck-remove&quot;]/div[@class=&quot;panel fs-tabset&quot;]/div[@class=&quot;panel-body fs-tabset-head&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tab-set&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/div[@class=&quot;panel-body fs-tabset-head&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tab-set&quot;]/div[@class=&quot;fs-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane fs-scope active&quot;]/div[@class=&quot;panel-body fs-scope&quot;]/fs-form[@class=&quot;fs-valid-patterncheck fs-valid-emailcheck fs-valid-maxlength fs-invalid fs-invalid-required fs-dirty fs-valid-parse fs-pending-add fs-invalid-remove fs-invalid-required-remove fs-valid-maxlength-remove fs-valid-patterncheck-remove&quot;]/div[@class=&quot;fs-scope&quot;]/fs-layout[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsLayout container-fluid&quot;]/div[@class=&quot;row panel-group&quot;]/fs-group[@class=&quot;fs-scope fs-isolate-scope fsGroup&quot;]/div[@class=&quot;panel panel-default fs-scope anonymous col-md-12 col-xs-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row fs-scope subRow&quot;]/fs-grid[@class=&quot;fs-scope fs-isolate-scope fsGrid&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12&quot;]/fs-text[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsText form-group fs-scope&quot;]/div[@class=&quot;col-md-0&quot;]/div[@class=&quot;edit&quot;]/input[@class=&quot;textInput form-control input-sm fs-valid fs-valid-maxlength&quot;]</value>
      <webElementGuid>d0a70ed8-50bc-4d95-8fcf-300b4b994667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'companyAddr1' and @fs-model = 'fsComponentCtrl.fsGridModel.companyAddr1' and @placeholder = 'Enter']</value>
      <webElementGuid>6d3a2451-cc1c-4a9e-bfa0-d69f9b93aff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='companyAddr1']</value>
      <webElementGuid>d7f3d0ce-3829-4432-afea-9095898f50b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fs-group[4]/div/div[2]/div/fs-grid/div/fs-text/div/div/div/input</value>
      <webElementGuid>67f83512-dfcc-440c-84dc-95df339ef6b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
