<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmailAddressField</name>
   <tag></tag>
   <elementGuidId>24c1b2ad-d9ba-4e78-b469-648670e0e7a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;companyEmail&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'companyEmail' and @fs-model = 'fsComponentCtrl.fsGridModel.companyEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54d76256-f9b6-45eb-89ac-aa2209406756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b53113a-e2f9-4cac-a5d2-bbb1e8fcf5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput form-control input-sm fs-valid-emailcheck fs-valid fs-valid-maxlength</value>
      <webElementGuid>451e1b00-42d9-43d3-9e6a-86339b696ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyEmail</value>
      <webElementGuid>ce9b4faf-1da3-4787-ad0a-b855377fed4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-model</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridModel.companyEmail</value>
      <webElementGuid>49580f28-812c-433b-ae55-e22b7a7af9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-model-options</name>
      <type>Main</type>
      <value>{ updateOn: fsComponentCtrl.fsGridConfig.updateOn}</value>
      <webElementGuid>003a27fb-d59e-4b7b-a5e4-9712dfd1b33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-trim</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1303cd30-5543-42d6-860a-7aa1a4492acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-tooltip-template</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.tooltipTemplateUrl</value>
      <webElementGuid>b130c385-ade0-4476-9c8b-e09dc60926fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-enable</name>
      <type>Main</type>
      <value>!!fsComponentCtrl.fsGridCtrl.getTooltipMessage(fsComponentCtrl.fsGridConfig)</value>
      <webElementGuid>412ee506-09c2-46ba-86e1-20de602dba0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-class</name>
      <type>Main</type>
      <value>input-tooltip</value>
      <webElementGuid>87a11c95-c6b7-48bd-a59f-778cdaf7df2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-trigger</name>
      <type>Main</type>
      <value>'focus keyup paste cut'</value>
      <webElementGuid>623e9c95-5c5a-4ffa-9dde-1275e4236d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-append-to-body</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dfb51020-568b-481f-a9a4-fdc01c8537b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>top-right</value>
      <webElementGuid>8e93620c-b25d-466d-a863-8299d08413ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-uppercase</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.uppercase</value>
      <webElementGuid>6b1975b6-5208-4679-99cc-b26fca7643c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-grid-filter</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.filter</value>
      <webElementGuid>0ce831c7-d948-4021-a78e-682414a82e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-grid-prefix</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.prefix</value>
      <webElementGuid>d51a79f6-b916-4806-8b33-904ce43cc95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-focus</name>
      <type>Main</type>
      <value>focus=true</value>
      <webElementGuid>78df69c4-0c30-4ff7-bda5-34671679e782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-blur</name>
      <type>Main</type>
      <value>focus=false</value>
      <webElementGuid>15e4abc4-8e02-4f2c-8869-062dfd50a717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fs-scope&quot;]/body[@class=&quot;app fs-scope v-scroll&quot;]/div[@class=&quot;app-view fs-scope&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/form[@class=&quot;fs-valid-patterncheck fs-valid-emailcheck fs-valid-maxlength fs-invalid fs-invalid-required fs-dirty fs-valid-parse fs-pending-add fs-invalid-remove fs-invalid-required-remove fs-valid-maxlength-remove fs-valid-patterncheck-remove&quot;]/div[@class=&quot;panel fs-tabset&quot;]/div[@class=&quot;panel-body fs-tabset-head&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tab-set&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/div[@class=&quot;panel-body fs-tabset-head&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tab-set&quot;]/div[@class=&quot;fs-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane fs-scope active&quot;]/div[@class=&quot;panel-body fs-scope&quot;]/fs-form[@class=&quot;fs-valid-patterncheck fs-valid-emailcheck fs-valid-maxlength fs-invalid fs-invalid-required fs-dirty fs-valid-parse fs-pending-add fs-invalid-remove fs-invalid-required-remove fs-valid-maxlength-remove fs-valid-patterncheck-remove&quot;]/div[@class=&quot;fs-scope&quot;]/fs-layout[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsLayout container-fluid&quot;]/div[@class=&quot;row panel-group&quot;]/fs-group[@class=&quot;fs-scope fs-isolate-scope fsGroup&quot;]/div[@class=&quot;panel panel-default fs-scope anonymous col-md-12 col-xs-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row fs-scope&quot;]/fs-grid[@class=&quot;fs-scope fs-isolate-scope fsGrid&quot;]/div[@class=&quot;col-md-3 col-sm-12 col-xs-12&quot;]/fs-text[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsText form-group fs-scope&quot;]/div[@class=&quot;col-md-0&quot;]/div[@class=&quot;edit&quot;]/input[@class=&quot;textInput form-control input-sm fs-valid-emailcheck fs-valid fs-valid-maxlength&quot;]</value>
      <webElementGuid>fc73c0ac-0d80-45e3-a36b-2d13d1c47559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'companyEmail' and @fs-model = 'fsComponentCtrl.fsGridModel.companyEmail']</value>
      <webElementGuid>7f74aa2b-40a9-442b-a488-16c5d761a51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='companyEmail']</value>
      <webElementGuid>e5f0a480-030e-4b91-9607-f0abec162ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fs-group[4]/div/div[2]/div[3]/fs-grid/div/fs-text/div/div/div/input</value>
      <webElementGuid>2043730a-5ac5-415c-8c07-4c25f0db1ea7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
