<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TimezoneField</name>
   <tag></tag>
   <elementGuidId>72408a49-c569-4d97-ab42-49b774bf8ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'fsComponentCtrl.timeZoneViewModel.label' and @placeholder = 'Select']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'fsComponentCtrl.timeZoneViewModel.label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fsComponentCtrl.timeZoneViewModel.label&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12b0642b-f71d-4d2f-8d8c-62090b26f249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce42b367-62a2-41a3-ab7f-c5ab62fa8f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${spanasiariyadh}</value>
      <webElementGuid>a36a718e-22d9-49c6-ab8b-c80c334532af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>3c10aa57-d590-4ec2-b85d-17a608f51ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fsComponentCtrl.timeZoneViewModel.label</value>
      <webElementGuid>041ba0ff-f8df-4e83-bd19-235d8ea63940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>e1c7af22-273f-41e6-8ca6-64ed60de9038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-tooltip-template</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.tooltipTemplateUrl</value>
      <webElementGuid>8088d263-1cf7-4e70-bb68-8e996024d221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-enable</name>
      <type>Main</type>
      <value>!!fsComponentCtrl.fsGridCtrl.getTooltipMessage(fsComponentCtrl.fsGridConfig)</value>
      <webElementGuid>42a50cab-b992-4ccd-8e88-e3df1976520a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-class</name>
      <type>Main</type>
      <value>input-tooltip</value>
      <webElementGuid>43027807-c79f-4782-a598-728d57fccb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-trigger</name>
      <type>Main</type>
      <value>'focus keyup paste cut'</value>
      <webElementGuid>fa5c9c0b-ae3b-40c8-b7fb-f28d241efc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-append-to-body</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60cf875a-dc84-4456-a312-0a93a0226387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>top-right</value>
      <webElementGuid>768dbadb-80ff-4177-84fd-029c39a139f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fs-scope&quot;]/body[@class=&quot;app fs-scope v-scroll&quot;]/div[@class=&quot;app-view fs-scope&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/form[@class=&quot;fs-valid-patterncheck fs-valid-emailcheck fs-valid-maxlength fs-invalid fs-invalid-required fs-dirty fs-valid-parse fs-pending-add fs-invalid-remove fs-invalid-required-remove fs-valid-maxlength-remove fs-valid-patterncheck-remove&quot;]/div[@class=&quot;panel fs-tabset&quot;]/div[@class=&quot;panel-body fs-tabset-head&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tab-set&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/div[@class=&quot;panel-body fs-tabset-head&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tab-set&quot;]/div[@class=&quot;fs-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane fs-scope active&quot;]/div[@class=&quot;panel-body fs-scope&quot;]/fs-form[@class=&quot;fs-valid-patterncheck fs-valid-emailcheck fs-valid-maxlength fs-invalid fs-invalid-required fs-dirty fs-valid-parse fs-pending-add fs-invalid-remove fs-invalid-required-remove fs-valid-maxlength-remove fs-valid-patterncheck-remove&quot;]/div[@class=&quot;fs-scope&quot;]/fs-layout[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsLayout container-fluid&quot;]/div[@class=&quot;row panel-group&quot;]/fs-group[@class=&quot;fs-scope fs-isolate-scope fsGroup&quot;]/div[@class=&quot;panel panel-default fs-scope anonymous col-md-12 col-xs-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row fs-scope subRow&quot;]/fs-grid[@class=&quot;fs-scope fs-isolate-scope fsGrid&quot;]/div[@class=&quot;col-md-3 col-sm-12 col-xs-12&quot;]/fs-custom-select[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsCustomSelect form-group fs-scope&quot;]/div[@class=&quot;dropdown col-md-0&quot;]/div[@class=&quot;edit input-group fs-scope dropdown-toggle&quot;]/input[@class=&quot;form-control input-sm&quot;]</value>
      <webElementGuid>a46f4fcf-56a7-4457-9749-59355ad01864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fsComponentCtrl.timeZoneViewModel.label' and @placeholder = 'Select']</value>
      <webElementGuid>fb99c98f-4622-4b71-949c-22e6398d13de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fsComponentCtrl.timeZoneViewModel.label']</value>
      <webElementGuid>ef8de0b8-beb2-40a1-9fbc-b3189abc60b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fs-group[5]/div/div[2]/div/fs-grid/div/fs-custom-select/div/div/div/input</value>
      <webElementGuid>e12e3cf0-04dc-4a47-8d07-7d83bbfec1d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
