<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WebURLField</name>
   <tag></tag>
   <elementGuidId>4b9bd679-363d-4123-9866-398967e1f139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;companyWWW&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'companyWWW' and @fs-model = 'fsComponentCtrl.fsGridModel.companyWWW']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'companyWWW' and @fs-model = 'fsComponentCtrl.fsGridModel.companyWWW' and @placeholder = 'Enter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>695c8715-01c9-4c8f-82ef-ef72a533259a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0423c9ff-b4e2-45d7-a4c7-3a0a3856b8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput form-control input-sm fs-valid-maxlength fs-valid fs-valid-patterncheck</value>
      <webElementGuid>75ceeb3e-8931-4643-b105-423e848beaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyWWW</value>
      <webElementGuid>5a56ba60-822e-47bd-9f43-aec3566d7589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-model</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridModel.companyWWW</value>
      <webElementGuid>04b5479f-e4c3-4120-8145-dea88f3e7ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-model-options</name>
      <type>Main</type>
      <value>{ updateOn: fsComponentCtrl.fsGridConfig.updateOn}</value>
      <webElementGuid>c7060dde-4dcc-414a-94e9-700a91f140e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-trim</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>da31c699-12f4-4e6d-b2cd-af64250a375d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-tooltip-template</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.tooltipTemplateUrl</value>
      <webElementGuid>71400c15-f039-4984-8cc3-66a804d794e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-enable</name>
      <type>Main</type>
      <value>!!fsComponentCtrl.fsGridCtrl.getTooltipMessage(fsComponentCtrl.fsGridConfig)</value>
      <webElementGuid>ec472f4e-c351-4ed6-be4b-8b04c6e1adb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-class</name>
      <type>Main</type>
      <value>input-tooltip</value>
      <webElementGuid>b5a7684f-f51a-4dcd-b7d5-8a31b9d9b393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-trigger</name>
      <type>Main</type>
      <value>'focus keyup paste cut'</value>
      <webElementGuid>593babc7-7c64-40d0-9f50-61e7fb80faa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-append-to-body</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2fe16872-8f0d-45e3-b95e-f1a061039b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>top-right</value>
      <webElementGuid>30c9f0b7-8176-4f11-8cd8-eefe44bb3a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-uppercase</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.uppercase</value>
      <webElementGuid>8bd9c0b1-10a5-4f73-a072-2b52fae4bbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-grid-filter</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.filter</value>
      <webElementGuid>c2608be4-c618-4ac0-a2fa-3ebe25a2f464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>58452020-d242-4fd3-ae0c-a918194a1e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-grid-prefix</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.prefix</value>
      <webElementGuid>0c7247b7-1d8e-4e21-8769-30fb44fa1eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-focus</name>
      <type>Main</type>
      <value>focus=true</value>
      <webElementGuid>74f5f239-6fb4-45da-ae29-7c25f76e920d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fs-blur</name>
      <type>Main</type>
      <value>focus=false</value>
      <webElementGuid>51189fec-ea7d-461e-a28c-4d0e10b432f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fs-scope&quot;]/body[@class=&quot;app fs-scope v-scroll&quot;]/div[@class=&quot;app-view fs-scope&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/form[@class=&quot;fs-valid-patterncheck fs-valid-emailcheck fs-valid-maxlength fs-invalid fs-invalid-required fs-dirty fs-valid-parse fs-pending-add fs-invalid-remove fs-invalid-required-remove fs-valid-maxlength-remove fs-valid-patterncheck-remove&quot;]/div[@class=&quot;panel fs-tabset&quot;]/div[@class=&quot;panel-body fs-tabset-head&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tab-set&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/div[@class=&quot;panel-body fs-tabset-head&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tab-set&quot;]/div[@class=&quot;fs-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane fs-scope active&quot;]/div[@class=&quot;panel-body fs-scope&quot;]/fs-form[@class=&quot;fs-valid-patterncheck fs-valid-emailcheck fs-valid-maxlength fs-invalid fs-invalid-required fs-dirty fs-valid-parse fs-pending-add fs-invalid-remove fs-invalid-required-remove fs-valid-maxlength-remove fs-valid-patterncheck-remove&quot;]/div[@class=&quot;fs-scope&quot;]/fs-layout[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsLayout container-fluid&quot;]/div[@class=&quot;row panel-group&quot;]/fs-group[@class=&quot;fs-scope fs-isolate-scope fsGroup&quot;]/div[@class=&quot;panel panel-default fs-scope anonymous col-md-12 col-xs-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row fs-scope subRow&quot;]/fs-grid[@class=&quot;fs-scope fs-isolate-scope fsGrid&quot;]/div[@class=&quot;col-md-9 col-sm-12 col-xs-12&quot;]/fs-text[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsText form-group fs-scope&quot;]/div[@class=&quot;col-md-0&quot;]/div[@class=&quot;edit&quot;]/input[@class=&quot;textInput form-control input-sm fs-valid-maxlength fs-valid fs-valid-patterncheck&quot;]</value>
      <webElementGuid>426e7180-78c4-4410-bcb7-13d137ab56fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'companyWWW' and @fs-model = 'fsComponentCtrl.fsGridModel.companyWWW' and @placeholder = 'Enter']</value>
      <webElementGuid>420bbb9c-c3f3-449e-9cbb-4e16da81f322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='companyWWW']</value>
      <webElementGuid>93f74dc2-e582-4076-a6b1-27cee7582b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fs-grid/div/fs-text/div/div/div/input</value>
      <webElementGuid>26cd7589-244d-4106-bcd0-427d23692b12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
