<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CompanyCodeField</name>
   <tag></tag>
   <elementGuidId>0086dc60-cf9b-4454-979d-f0caa3a5f628</elementGuidId>
   <imagePath>Screenshots/Targets/bpt_Companypage/CompanyPage_CompanyCodeList.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/bpt_Companypage/CompanyPage_CompanyCodeList.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fsComponentCtrl.companyCodeViewModel.label&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fsComponentCtrl.companyCodeViewModel.label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Company Code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19976091-18b2-4055-b942-47c1b8395013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>003f2d9d-8935-493c-adb2-92637970ac87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>8dd3239b-f950-4731-8c63-d96389ad619c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fsComponentCtrl.companyCodeViewModel.label</value>
      <webElementGuid>2fd923c7-f317-4eff-8ae9-73c7d4830d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company Code</value>
      <webElementGuid>49a7b214-1909-4e96-8175-c42ae878f71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-tooltip-template</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.tooltipTemplateUrl</value>
      <webElementGuid>f5b23ccf-75a3-4408-aa16-b9f2fa0bcd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-enable</name>
      <type>Main</type>
      <value>!!fsComponentCtrl.fsGridCtrl.getTooltipMessage(fsComponentCtrl.fsGridConfig)</value>
      <webElementGuid>42254631-5466-43df-9dd2-c3fe7de40dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-class</name>
      <type>Main</type>
      <value>input-tooltip</value>
      <webElementGuid>dfc46968-4c63-4ca5-bc27-0d65f64a32a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-trigger</name>
      <type>Main</type>
      <value>'focus keyup paste cut'</value>
      <webElementGuid>58268026-7d01-429f-b71e-3aaf9f87bfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-append-to-body</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce02ad67-19af-48c6-9554-165d32834894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>top-right</value>
      <webElementGuid>f006e945-d4bd-4d2b-a79c-7aa86d6afc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fs-scope&quot;]/body[@class=&quot;app fs-scope v-scroll&quot;]/div[@class=&quot;app-view fs-scope&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/form[@class=&quot;fs-pristine fs-valid-patterncheck fs-valid fs-valid-maxlength fs-valid-min fs-valid-max fs-valid-required&quot;]/div[1]/fs-layout[@class=&quot;fs-isolate-scope&quot;]/div[@class=&quot;fsLayout container-fluid&quot;]/div[@class=&quot;row panel-group&quot;]/fs-group[@class=&quot;fs-scope fs-isolate-scope fsGroup&quot;]/div[@class=&quot;panel panel-default fs-scope anonymous title-no-bg operator-group inquiry-operator-2 col-md-12 col-xs-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row fs-scope&quot;]/fs-grid[@class=&quot;fs-scope fs-isolate-scope fsGrid&quot;]/div[@class=&quot;col-md-2 col-sm-12 col-xs-12&quot;]/fs-custom-select[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsCustomSelect form-group fs-scope&quot;]/div[@class=&quot;dropdown col-md-0&quot;]/div[@class=&quot;edit input-group fs-scope dropdown-toggle&quot;]/input[@class=&quot;form-control input-sm&quot;]</value>
      <webElementGuid>e07c0d0a-c934-46f9-bd54-09670af35a6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fsComponentCtrl.companyCodeViewModel.label']</value>
      <webElementGuid>aa1eac14-d087-4f73-8980-a643fce3ac0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fs-grid[2]/div/fs-custom-select/div/div/div/input</value>
      <webElementGuid>491b93b4-26ef-4063-8a87-a8d01734c615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fsComponentCtrl.companyCodeViewModel.label' and @placeholder = 'Company Code']</value>
      <webElementGuid>e02c45b9-5ab6-444e-940d-fe7706aaa86b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
