<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CompanyCodeField</name>
   <tag></tag>
   <elementGuidId>0086dc60-cf9b-4454-979d-f0caa3a5f628</elementGuidId>
   <imagePath>Screenshots/Targets/bpt_Companypage/CompanyPage_CompanyCodeList.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='companyCodeKeyWord']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/bpt_Companypage/CompanyPage_CompanyCodeList.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fsComponentCtrl.companyCodeViewModel.label&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Company Code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a670a54-cc19-4176-9675-03e9d8f9ba6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41cea1c8-17a2-4ab9-b54c-2a3930258e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>b1705c7e-3778-453e-a31b-4d7f8b111e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fsComponentCtrl.companyCodeViewModel.label</value>
      <webElementGuid>2b780125-f0b7-4e63-88fc-ca9c5248af78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company Code</value>
      <webElementGuid>4828c580-c63a-4697-9ae0-62e11cb33779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-tooltip-template</name>
      <type>Main</type>
      <value>fsComponentCtrl.fsGridConfig.tooltipTemplateUrl</value>
      <webElementGuid>a32ea14a-6d10-48b1-a395-09863a12e217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-enable</name>
      <type>Main</type>
      <value>!!fsComponentCtrl.fsGridCtrl.getTooltipMessage(fsComponentCtrl.fsGridConfig)</value>
      <webElementGuid>fd45a9b6-3c57-42e4-941f-f33b32dbb204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-class</name>
      <type>Main</type>
      <value>input-tooltip</value>
      <webElementGuid>a2ce7817-8984-4fbe-979d-a2c6f37c6f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-trigger</name>
      <type>Main</type>
      <value>'focus keyup paste cut'</value>
      <webElementGuid>488337c0-973c-4170-a5ae-eaf233b9d6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-append-to-body</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>be084d6a-7595-47df-b529-5f5294de807a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>top-right</value>
      <webElementGuid>1a49b1ba-c8a2-4026-aa47-5e2c4a000682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fs-scope&quot;]/body[@class=&quot;app fs-scope v-scroll&quot;]/div[@class=&quot;app-view fs-scope&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;fs-scope&quot;]/div[@class=&quot;bpt-form fs-scope&quot;]/form[@class=&quot;fs-pristine fs-valid-patterncheck fs-valid fs-valid-maxlength fs-valid-min fs-valid-max fs-valid-required&quot;]/div[1]/fs-layout[@class=&quot;fs-isolate-scope&quot;]/div[@class=&quot;fsLayout container-fluid&quot;]/div[@class=&quot;row panel-group&quot;]/fs-group[@class=&quot;fs-scope fs-isolate-scope fsGroup&quot;]/div[@class=&quot;panel panel-default fs-scope anonymous title-no-bg operator-group inquiry-operator-2 col-md-12 col-xs-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row fs-scope&quot;]/fs-grid[@class=&quot;fs-scope fs-isolate-scope fsGrid&quot;]/div[@class=&quot;col-md-2 col-sm-12 col-xs-12&quot;]/fs-custom-select[@class=&quot;fs-scope fs-isolate-scope&quot;]/div[@class=&quot;fsCustomSelect form-group fs-scope&quot;]/div[@class=&quot;dropdown col-md-0&quot;]/div[@class=&quot;edit input-group fs-scope dropdown-toggle&quot;]/input[@class=&quot;form-control input-sm&quot;]</value>
      <webElementGuid>4ad76fd7-f0f9-43d3-811b-5f2fd6f5d630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fsComponentCtrl.companyCodeViewModel.label']</value>
      <webElementGuid>b1f176f5-cb3f-48ac-b09a-e5d01813e07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fs-grid[2]/div/fs-custom-select/div/div/div/input</value>
      <webElementGuid>698cdb8b-f22a-44a5-a396-4bd9dd839ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fsComponentCtrl.companyCodeViewModel.label' and @placeholder = 'Company Code']</value>
      <webElementGuid>c7e25b2a-625d-483b-9cbf-48f063087c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
