<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StatusLabel</name>
   <tag></tag>
   <elementGuidId>8946f16f-e98a-4506-a811-b5da8e699a8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='rowgroup'][2]/div/div/div[1]/div[1]/div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1716294780469-0-uiGrid-00C5-cell > div.ui-grid-cell-contents.fs-scope.text-left > span.fs-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;Verified&quot;i] >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>823ff17c-8991-4ae1-b24b-c00d9f1e1640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-binding</value>
      <webElementGuid>160c7567-3249-424f-b33f-a6f3b320f251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verified </value>
      <webElementGuid>961ab3a2-a101-4efc-afcb-2e4a51a521cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1716294780469-0-uiGrid-00C5-cell&quot;)/div[@class=&quot;ui-grid-cell-contents fs-scope text-left&quot;]/span[@class=&quot;fs-binding&quot;]</value>
      <webElementGuid>4c62c382-bdc7-4b1e-ae94-ad4705fd17c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1716294780469-0-uiGrid-00C5-cell']/div/span</value>
      <webElementGuid>22bcb495-2eb7-41e5-9b22-488d42f591b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/preceding::span[1]</value>
      <webElementGuid>d77df971-a384-40b1-beaa-9b7fddde0f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::span[15]</value>
      <webElementGuid>e7f7f05d-f54f-4b98-b93d-7d9360db65b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span</value>
      <webElementGuid>1bce8dfd-a998-4d6e-8bc3-cd2cfb6c681f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Verified ' or . = 'Verified ')]</value>
      <webElementGuid>13e3ad66-770a-4834-9c02-c86375f7c878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
