<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CompanyField</name>
   <tag></tag>
   <elementGuidId>60586985-737c-47ca-ae8b-530d7d52410c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;companyCode&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'companyCode']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Company' and @name = 'companyCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d88a7e0-b047-4b56-a505-bd760b74d3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ptbank-logo-input</value>
      <webElementGuid>ff1119ff-53bd-4550-b4bc-654fca2a2d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>94b590f2-3904-46f0-87a2-49e26e4f55f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyCode</value>
      <webElementGuid>99947e2d-ca9f-4ebe-a1b9-4ece834a1130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();showVerifyCode(document.forms[0]);</value>
      <webElementGuid>d91e6fe4-dfff-4c3d-b483-a8c850b201f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginPage&quot;)/table[@class=&quot;fulll-width&quot;]/tbody[1]/tr[1]/td[@class=&quot;ptbank-logo-line&quot;]/input[@class=&quot;ptbank-logo-input&quot;]</value>
      <webElementGuid>713f8ba6-8b61-462d-b1c5-48cc62efd906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Company' and @name = 'companyCode']</value>
      <webElementGuid>b26c3f3d-c6ea-47ea-8dc2-a8b5ed21a6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='companyCode']</value>
      <webElementGuid>93d1ad79-5b72-4312-81f8-2ff71befac9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginPage']/table/tbody/tr/td/input</value>
      <webElementGuid>595e827a-100a-4d56-a36e-99f860993ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>70055e9f-aef0-4126-b02b-ba7892852136</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
